version: 0.2
phases:
  pre_build:
    commands:
      - echo Building the Docker image...
      - docker build -t <IMAGE_NAME>:<IMAGE_TAG> .
  build:
    commands:
      - echo Skipping push to ECR.
artifacts:
  files:
    - appspec.yml
    - Dockerrun.aws.json
